# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libFFI.

FIND_PATH(FFI_INCLUDE_DIR ffi.h /usr/lib/libffi-3.0.9/include)

SET(FFI_NAMES ${FFI_NAMES} ffi libffi)
FIND_LIBRARY(FFI_LIBRARY NAMES ${FFI_NAMES} PATH /usr/lib/libffi)

IF(FFI_INCLUDE_DIR AND FFI_LIBRARY)
	SET(FFI_FOUND TRUE)
ENDIF(FFI_INCLUDE_DIR AND FFI_LIBRARY)

IF(FFI_FOUND)
	IF(NOT FFI_FIND_QUIETLY)
		MESSAGE(STATUS "Found FFI: ${FFI_LIBRARY}")
	ENDIF (NOT FFI_FIND_QUIETLY)
ELSE(FFI_FOUND)
	IF(FFI_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find FFI")
	ENDIF(FFI_FIND_REQUIRED)
ENDIF (FFI_FOUND)
