# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libglib.

FIND_PATH(GLIB_INCLUDE_DIR glib-2.0/glib.h /usr/lib/glib-2.0/include/glibconfig.h)

SET(GLIB_NAMES ${GLIB_NAMES} glib-2.0 libglib-2.0)
FIND_LIBRARY(GLIB_LIBRARY NAMES ${GLIB_NAMES} PATH)

IF(GLIB_INCLUDE_DIR AND GLIB_LIBRARY)
	SET(GLIB_FOUND TRUE)
ENDIF(GLIB_INCLUDE_DIR AND GLIB_LIBRARY)

IF(GLIB_FOUND)
	IF(NOT GLIB_FIND_QUIETLY)
		MESSAGE(STATUS "Found GLIB: ${GLIB_LIBRARY}")
	ENDIF (NOT GLIB_FIND_QUIETLY)
ELSE(GLIB_FOUND)
	IF(GLIB_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find GLIB")
	ENDIF(GLIB_FIND_REQUIRED)
ENDIF (GLIB_FOUND)
