# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find OpenSSL.

FIND_PATH(SSL_INCLUDE_DIR openssl/ssl.h)

SET(SSL_NAMES ${SSL_NAMES} ssl)
FIND_LIBRARY(SSL_LIBRARY NAMES ${SSL_NAMES} PATH /usr/lib)

IF(SSL_INCLUDE_DIR AND SSL_LIBRARY)
	SET(SSL_FOUND TRUE)
ENDIF(SSL_INCLUDE_DIR AND SSL_LIBRARY)

IF(SSL_FOUND)
	IF(NOT SSL_FIND_QUIETLY)
		MESSAGE(STATUS "Found SSL: ${SSL_LIBRARY}")
	ENDIF (NOT SSL_FIND_QUIETLY)
ELSE(SSL_FOUND)
	IF(SSL_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find OpenSSL")
	ENDIF(SSL_FIND_REQUIRED)
ENDIF (SSL_FOUND)
