# Find glfw

IF(GLFW_INCLUDE_DIR AND GLFW_LIBRARY)
	set(GLFW_FIND_QUIETLY TRUE)
ENDIF(GLFW_INCLUDE_DIR AND GLFW_LIBRARY)

FIND_PATH(GLFW_INCLUDE_DIR GL/glfw.h)

SET(GLFW_NAMES ${GLFW_NAMES} libglfwdll libglfw glfw)
FIND_LIBRARY(GLFW_LIBRARY NAMES ${GLFW_NAMES} PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLFW DEFAULT_MSG GLFW_LIBRARY GLFW_INCLUDE_DIR)
mark_as_advanced(GLFW_INCLUDE_DIR GLFW_LIBRARY)
