# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libclutter.

FIND_PATH(CLUTTER_INCLUDE_DIR clutter.h)

SET(CLUTTER_NAMES ${CLUTTER_NAMES} clutter libclutter)
FIND_LIBRARY(CLUTTER_LIBRARY NAMES ${CLUTTER_NAMES} PATH)

IF(CLUTTER_INCLUDE_DIR AND CLUTTER_LIBRARY)
	SET(CLUTTER_FOUND TRUE)
ENDIF(CLUTTER_INCLUDE_DIR AND CLUTTER_LIBRARY)

IF(CLUTTER_FOUND)
	IF(NOT Clutter_FIND_QUIETLY)
		MESSAGE(STATUS "Found Clutter: ${CLUTTER_LIBRARY}")
	ENDIF (NOT Clutter_FIND_QUIETLY)
ELSE(CLUTTER_FOUND)
	IF(Clutter_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find clutter")
	ENDIF(Clutter_FIND_REQUIRED)
ENDIF (CLUTTER_FOUND)
