# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libsndfile.

FIND_PATH(SNDFILE_INCLUDE_DIR sndfile.h)

SET(SNDFILE_NAMES ${SNDFILE_NAMES} sndfile libsndfile)
FIND_LIBRARY(SNDFILE_LIBRARY NAMES ${SNDFILE_NAMES} PATH)

IF(SNDFILE_INCLUDE_DIR AND SNDFILE_LIBRARY)
	SET(SNDFILE_FOUND TRUE)
ENDIF(SNDFILE_INCLUDE_DIR AND SNDFILE_LIBRARY)

IF(SNDFILE_FOUND)
	IF(NOT Sndfile_FIND_QUIETLY)
		MESSAGE(STATUS "Found Sndfile: ${SNDFILE_LIBRARY}")
	ENDIF (NOT Sndfile_FIND_QUIETLY)
ELSE(SNDFILE_FOUND)
	IF(Sndfile_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find sndfile")
	ENDIF(Sndfile_FIND_REQUIRED)
ENDIF (SNDFILE_FOUND)
