# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libedit

FIND_PATH(EDIT_INCLUDE_DIR histedit.h)

SET(EDIT_NAMES ${EDIT_NAMES} edit libedit)
FIND_LIBRARY(EDIT_LIBRARY NAMES ${EDIT_NAMES} PATH)

IF(EDIT_INCLUDE_DIR AND EDIT_LIBRARY)
	SET(EDIT_FOUND TRUE)
ENDIF(EDIT_INCLUDE_DIR AND EDIT_LIBRARY)

IF(EDIT_FOUND)
	IF(NOT EDIT_FIND_QUIETLY)
		MESSAGE(STATUS "Found EDIT: ${EDIT_LIBRARY}")
	ENDIF (NOT EDIT_FIND_QUIETLY)
ELSE(EDIT_FOUND)
	IF(EDIT_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find EDIT")
	ENDIF(EDIT_FIND_REQUIRED)
ENDIF(EDIT_FOUND)
