/*
 *
 * GLE Constants
 *
 */

typedef struct t_ioGLE_constTable {
	char *name;
	int value;
} t_ioGLE_constTable;


t_ioGLE_constTable ioGLE_constTable[] = {

/* Defines for tubing join styles */
	{"TUBE_JN_RAW",TUBE_JN_RAW},
	{"TUBE_JN_ANGLE",TUBE_JN_ANGLE},
	{"TUBE_JN_CUT",TUBE_JN_CUT},
	{"TUBE_JN_ROUND",TUBE_JN_ROUND},
	{"TUBE_JN_MASK",TUBE_JN_MASK},
	{"TUBE_JN_CAP",TUBE_JN_CAP},

/* Determine how normal vectors are to be handled */
	{"TUBE_NORM_FACET",TUBE_NORM_FACET},
	{"TUBE_NORM_EDGE",TUBE_NORM_EDGE},
	{"TUBE_NORM_PATH_EDGE",TUBE_NORM_PATH_EDGE},
	{"TUBE_NORM_MASK",TUBE_NORM_MASK},

/* Closed or open countours */
	{"TUBE_CONTOUR_CLOSED",TUBE_CONTOUR_CLOSED},

/* Other */
	{"GLE_TEXTURE_ENABLE",GLE_TEXTURE_ENABLE},
	{"GLE_TEXTURE_STYLE_MASK",GLE_TEXTURE_STYLE_MASK},
	{"GLE_TEXTURE_VERTEX_FLAT",GLE_TEXTURE_VERTEX_FLAT},
	{"GLE_TEXTURE_NORMAL_FLAT",GLE_TEXTURE_NORMAL_FLAT},
	{"GLE_TEXTURE_VERTEX_CYL",GLE_TEXTURE_VERTEX_CYL},
	{"GLE_TEXTURE_NORMAL_CYL",GLE_TEXTURE_NORMAL_CYL},
	{"GLE_TEXTURE_VERTEX_SPH",GLE_TEXTURE_VERTEX_SPH},
	{"GLE_TEXTURE_NORMAL_SPH",GLE_TEXTURE_NORMAL_SPH},
	{"GLE_TEXTURE_VERTEX_MODEL_FLAT",GLE_TEXTURE_VERTEX_MODEL_FLAT},
	{"GLE_TEXTURE_NORMAL_MODEL_FLAT",GLE_TEXTURE_NORMAL_MODEL_FLAT},
	{"GLE_TEXTURE_VERTEX_MODEL_CYL",GLE_TEXTURE_VERTEX_MODEL_CYL},
	{"GLE_TEXTURE_NORMAL_MODEL_CYL",GLE_TEXTURE_NORMAL_MODEL_CYL},
	{"GLE_TEXTURE_VERTEX_MODEL_SPH",GLE_TEXTURE_VERTEX_MODEL_SPH},
	{"GLE_TEXTURE_NORMAL_MODEL_SPH",GLE_TEXTURE_NORMAL_MODEL_SPH},

	/* The end */
	{NULL,0},
};
