CCLDOUTFLAG := -o 
ifneq (,$(findstring Windows,$(SYS)))
    CCLDOUTFLAG := -Fe
endif

iofiles=$(wildcard io/*.io)

tools/io2c:
	$(CC) tools/io2c.c $(CCLDOUTFLAG)tools/io2c

all_begin: source/IoVMInit.c

source/IoVMInit.c: tools/io2c $(iofiles)
	./tools/io2c VMCode IoState_doString_ $(iofiles) > $@

all_end:
	

clean:
	-rm -f tools/io2c

test:
	
