include ../../Makefile.lib
CFLAGS += -DBUILDING_IOVM_DLL $(IOVMALLFLAGS)

#hasEditLib := $(wildcard ../../tools/editlib_test/editlib_test)
#ifneq ($(strip $(hasEditLib)),)
#CFLAGS += -DIO_HAS_EDITLIB
#endif
