CCLDOUTFLAG := -o 
ifneq (,$(findstring Windows,$(SYS)))
    CCLDOUTFLAG := -Fe
endif

tools/io2c:
	$(CC) tools/io2c.c $(CCLDOUTFLAG)tools/io2c

all_begin: tools/io2c
	./tools/io2c VMCode IoState_doString_ $(shell ls io/*.io) > source/IoVMInit.c

all_end:
	

clean:
	-rm -f tools/io2c

test:
	
